version: '3'

services:
  frontend:
    build: ./RoraimaFront
    container_name: roraima-frontend

    stdin_open: true
    tty: true
    volumes:
      - ./RoraimaFront/src:/usr/src/app/src
    environment:
        - CHOKIDAR_USEPOLLING=true
    command: yarn start
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on: 
      - mssql_db
      - es01
    networks: 
      roraima-network: 

  api:
    image: docker4job/roraimaproject:20200727115930
    container_name: roraima-api
    ports:
      - "6533:80"
    restart: unless-stopped
    depends_on: 
      - mssql_db
      - es01
    networks: 
      roraima-network: 
    environment:
      - CONNECTION_STRING=Server=mssql_db;Database=RoraimaDB;User Id=SA;Password=StrongPassword@123;
      - ES_CONNECTION_STRING=http://es01:9200
      - ENVMODE=DEBUG


  mssql_db:
    image: mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04
    user: root
    container_name: roraima-mssql-db
    volumes:
      - ./data:/var/opt/mssql/data
    ports:
      - "6462:1433"
    restart: unless-stopped
    environment:
      SA_PASSWORD: "StrongPassword@123"
      ACCEPT_EULA: "Y"
    depends_on: 
      - es01
    networks: 
      roraima-network: 

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: es01
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks: 
      roraima-network: 



  kib01:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks: 
      roraima-network: 

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local


networks:
  roraima-network:
    driver: bridge 
