version: '3'

services:
  api:
    image: docker4job/roraimaproject:latest
    container_name: roraima-api
    ports:
      - "6533:80"
    depends_on: 
      - mssql_db
    networks: 
      roraima-network:
  mssql_db:
    image: mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04
    user: root
    container_name: roraima-mssql-db
    volumes:
      - ./data:/var/opt/mssql/data
    ports:
      - "6462:1433"
    environment:
      SA_PASSWORD: "StrongPassword@123"
      ACCEPT_EULA: "Y"
    networks: 
      roraima-network:


networks: 
  roraima-network:
    driver: bridge

