version: '3'

services:
  frontend:
    build: ./RoraimaFront
    container_name: roraima-frontend

    stdin_open: true
    tty: true
    volumes:
      - ./RoraimaFront/src:/usr/src/app/src
    environment:
        - CHOKIDAR_USEPOLLING=true
    command: yarn start
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on: 
      - mssql_db
    networks: 
      roraima-network: 

  api:
    image: docker4job/roraimaproject:latest
    container_name: roraima-api
    ports:
      - "6533:80"
    restart: unless-stopped
    depends_on: 
      - mssql_db
    networks: 
      roraima-network:
  mssql_db:
    image: mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04
    user: root
    container_name: roraima-mssql-db
    volumes:
      - ./data:/var/opt/mssql/data
    ports:
      - "6462:1433"
    restart: unless-stopped
    environment:
      SA_PASSWORD: "StrongPassword@123"
      ACCEPT_EULA: "Y"
    networks: 
      roraima-network:


networks: 
  roraima-network:
    driver: bridge

